apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloudbox
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/cloudbox"
  SPRING_DATASOURCE_USERNAME: "daniil"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  MINIO_ENDPOINT: "http://minio:9000"