apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cloudbox
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
  SPRING_DATA_REDIS_PASSWORD: "CHANGE_ME"
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"